theme: jekyll-theme-minimal
title: Hariganesh Tangirala
description: Hello!

# These show up as tabs at the top
nav:
  - name: Home
    link: /
  - name: Projects
    link: /projects
  - name: Blog
    link: /blog
  - name: CV
    link: https://drive.google.com/file/d/1d6lKtPy-cd1OhS_BeaMKqAjuw0RzObWw/view?usp=sharing
